[features]
seeds = false
[programs.devnet]
nft_swap = "HkPrTq3GowSRncEcNSFppSftU2KfwWG69yqaajJQTDQz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/khacvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
